{% set name = "collate-sqllineage" %}
{% set version = "1.6.13" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/collate_sqllineage-{{ version }}.tar.gz
  sha256: fe5af5d12d8447335e2878f61754588d1e88c80024fd72a8bbe93a2415ef0e46

build:
  entry_points:
    - sqllineage = collate_sqllineage.cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - sqlparse >=0.4.4,<=0.5
    - networkx >=2.4
    - sqlfluff >=3.0.0,<3.1.0

test:
  imports:
    - collate_sqllineage
  commands:
    # - pip check fails right now
    - sqllineage --help
  requires:
    - python {{ python_min }}
    - pip

about:
  summary: Collate SQL Lineage for Analysis Tool powered by Python and sqlfluff based on sqllineage.
  home: https://github.com/reata/sqllineage
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
