{% set name = "collate-sqllineage" %}
{% set version = "1.6.21" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/collate_sqllineage-{{ version }}.tar.gz
  sha256: f4239dc8d7b8f287bab00ba2eb582d364c1e2d26ce94e5ae9a75b39361087b69

build:
  entry_points:
    - sqllineage = collate_sqllineage.cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - sqlparse >=0.4.4,<=0.5
    - networkx >=2.4
    - sqlfluff >=3.0.0,<3.1.0

test:
  imports:
    - collate_sqllineage
  commands:
    # - pip check fails right now
    - sqllineage --help
  requires:
    - python {{ python_min }}
    - pip

about:
  summary: Collate SQL Lineage for Analysis Tool powered by Python and sqlfluff based on sqllineage.
  home: https://github.com/reata/sqllineage
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
