# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  name: collate-sqllineage
  version: "2.1.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/collate_sqllineage-${{ version }}.tar.gz
  sha256: a1dd9a818bf978e1f1267e1f8a16ae1f209f66701ff8e70da461138b5d328190

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - sqllineage = collate_sqllineage.cli:main

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }},<4.0
    - sqlparse ==0.5.3
    - networkx >=2.4
    - collate-sqlfluff ==3.5.0
    - sqlglot ==29.0.1
tests:
  - python:
      imports:
        - collate_sqllineage
      python_version: ${{ python_min }}.*
      pip_check: true
  - requirements:
      run:
        - python ${{ python_min }}.*
        - pip
    script:
      - sqllineage --help

about:
  summary: Collate SQL Lineage for Analysis Tool powered by Python and sqlfluff based on sqllineage.
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/reata/sqllineage

extra:
  recipe-maintainers:
    - rxm7706
